### ISSUE TITLE
Morning session: Peer-to-peer code review - 08 FEB 2022

### ISSUE THREAD

**Issue by Sboursen** [mirouhml/awesome-books#3]
## Hi @mirouhml  , :wave: 

**We want to express our appreciation for your work. It looks nice, and for the most part responsive** :rocket:

**However, we noticed a few issues that are holding your work from attaining greatness:**

- [ ] **Remove duplicate books** - It would be nice to prevent the adding of a duplicate book that has the same author and title.

Please feel free to ask for any more clarification about the issues we raised.
Happy Coding! :rocket: 

![](https://media.giphy.com/media/j1Xyt3DHfJcmk/giphy.gif)

**Comment by mirouhml** [comment]
Thanks for the suggestion guys! I will work on it later.
